name: CI (Terraform plan/apply) and Deploy Java

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tf'
  pull_request:
    paths:
      - '**/*.tf'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # 1) Terraform: plan (runs on PRs and pushes to .tf)
  terraform:
    name: Terraform - Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Terraform Init
        run: terraform init -input=false

      - name: Check terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan -input=false -no-color -out=plan.tfplan

      - name: Upload plan artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: plan.tfplan

  # 2) Apply: only on push to main (depends on terraform job)
  apply:
    name: Terraform - Apply (main only)
    runs-on: ubuntu-latest
    needs: terraform
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Terraform Init
        run: terraform init -input=false

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: .

      - name: Terraform Apply
        run: |
          # If plan file doesn't exist, create and apply; otherwise apply the plan
          if [ -f plan.tfplan ]; then
            terraform apply -input=false -auto-approve plan.tfplan
          else
            terraform plan -input=false -no-color -out=plan.tfplan
            terraform apply -input=false -auto-approve plan.tfplan
          fi

  # 3) Deploy: run Ansible after apply completes successfully
  deploy:
    name: Deploy Java (Ansible)
    runs-on: ubuntu-latest
    needs: apply
    # Also ensure we only run deploy when apply ran on main push (protects PR runs)
    if: ${{ needs.apply.result == 'success' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install "ansible>=7.0"

      - name: Write SSH private key
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_KEY" > ./id_rsa
          chmod 600 ./id_rsa

      - name: Build inventory from HOSTS secret (or use inventory/hosts.ini)
        env:
          HOSTS: ${{ secrets.HOSTS }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          if [ -n "$HOSTS" ]; then
            rm -f ./inventory/hosts.ini || true
            mkdir -p ./inventory
            echo "[java_servers]" > ./inventory/hosts.ini
            IFS=',' read -ra ADDR <<< "$HOSTS"
            for h in "${ADDR[@]}"; do
              echo "${h} ansible_user=${SSH_USER}" >> ./inventory/hosts.ini
            done
            echo "Generated inventory:"
            cat ./inventory/hosts.ini
          else
            echo "Using repository inventory/hosts.ini"
            cat ./inventory/hosts.ini || true
          fi

      - name: Add hosts to known_hosts (ssh-keyscan)
        env:
          HOSTS: ${{ secrets.HOSTS }}
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          if [ -n "$HOSTS" ]; then
            IFS=',' read -ra ADDR <<< "$HOSTS"
            for h in "${ADDR[@]}"; do
              ssh-keygen -F "$h" || ssh-keyscan -H "$h" >> ~/.ssh/known_hosts || true
            done
          fi
          echo "known_hosts (head):"
          sed -n '1,10p' ~/.ssh/known_hosts || true

      - name: Run Ansible playbook (install Java)
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i ./inventory/hosts.ini playbooks/install-java.yml \
            --private-key ./id_rsa
