name: Deploy via AWS Keys (test)
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (from secrets)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Show identity (verify)
        run: aws sts get-caller-identity

      - name: Upload test file to S3 (verify permissions)
        run: |
          echo "deploy test from GH Actions $GITHUB_RUN_ID" > gh-deploy-test-${{ github.run_id }}.txt
          aws s3 cp gh-deploy-test-${{ github.run_id }}.txt s3://cuvil-deploy-bucket/
